// reports.js

App.pages['reports'] = {
    render() {
        const container = document.createElement('div');
        container.innerHTML = `
            <div class="actions-bar glass-panel" style="padding: 1rem; border-radius: 8px; display: flex; justify-content: space-between; align-items: center; gap: 1rem; flex-wrap: wrap;">
                <div id="inventory-status" style="display:flex; align-items:center; gap: 0.5rem">
                    <span class="status-badge status-pending">Checking Inventory Status...</span>
                </div>
                <div style="display: flex; gap: 0.75rem; align-items: center;">
                    <button class="btn btn-secondary" id="btn-export-csv" title="Download current live inventory balance as CSV">
                        <i class='bx bx-download'></i> Export CSV (Current Balance)
                    </button>
                    <button class="btn btn-primary" id="btn-generate-report">
                        <i class='bx bx-file'></i> Generate Inventory Report
                    </button>
                </div>
            </div>
            
            <div class="glass-panel table-container">
                <table id="reports-table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Report Name</th>
                            <th>Type</th>
                            <th>Generated By</th>
                            <th>Generated On</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr><td colspan="5" style="text-align: center;">Loading...</td></tr>
                    </tbody>
                </table>
            </div>
        `;
        return container;
    },

    async init() {
        this.checkInventoryStatus();
        this.loadReports();

        document.getElementById('btn-generate-report')?.addEventListener('click', () => {
            this.generateReport();
        });

        document.getElementById('btn-export-csv')?.addEventListener('click', () => {
            this.exportCsv();
        });
    },

    async checkInventoryStatus() {
        const statusEl = document.getElementById('inventory-status');
        try {
            const data = await Api.get('/reports/status');
            
            let statusClass = 'status-active';
            if (data.status !== 'READY') statusClass = 'status-pending';

            statusEl.innerHTML = `
                <span class="status-badge ${statusClass}">Inventory: ${data.status}</span>
                <span style="font-size: 0.85rem; color: var(--gray)">${data.message || ''}</span>
            `;
        } catch (error) {
            statusEl.innerHTML = `<span class="status-badge status-inactive">Status Unavailable</span>`;
        }
    },

    async loadReports() {
        const tbody = document.querySelector('#reports-table tbody');
        try {
            const data = await Api.get('/reports/');
            
            if (!data || data.length === 0) {
                tbody.innerHTML = `<tr><td colspan="5" style="text-align: center;">No reports generated yet.</td></tr>`;
                return;
            }

            tbody.innerHTML = data.map(r => `
                <tr>
                    <td>#${r.report_id}</td>
                    <td><strong>${Utils.escapeHtml(r.report_name)}</strong></td>
                    <td><span class="badge" style="position: relative; top:0; background: #e0e0e0; color: #333;">${r.report_type}</span></td>
                    <td>User #${r.generated_by}</td>
                    <td>${Utils.formatDate(r.generated_on)}</td>
                </tr>
            `).join('');
            
        } catch (error) {
            tbody.innerHTML = `<tr><td colspan="5" class="text-danger" style="text-align: center;">Failed to load reports: ${error.message}</td></tr>`;
        }
    },

    async generateReport() {
        const user = Auth.getUser();
        if (!user) return;

        const payload = {
            report_name: `Inventory Snapshot - ${new Date().toLocaleDateString()}`,
            report_type: 'Inventory',
            generated_by: user.id
        };

        const btn = document.getElementById('btn-generate-report');
        if (btn) {
            btn.disabled = true;
            btn.innerHTML = `<i class='bx bx-loader-alt bx-spin'></i> Generating...`;
        }

        try {
            const data = await Api.post('/reports/generate', payload);
            Utils.showToast(data.message, 'success');
            this.loadReports();
        } catch (error) {
            if (error.status === 423) {
                Utils.showToast("Report generation is temporarily unavailable while inventory is being updated.", "warning");
            } else {
                Utils.showToast(error.message || "Failed to generate report", "error");
            }
        } finally {
            if (btn) {
                btn.disabled = false;
                btn.innerHTML = `<i class='bx bx-file'></i> Generate Inventory Report`;
            }
        }
    },

    async exportCsv() {
        const btn = document.getElementById('btn-export-csv');
        if (btn) {
            btn.disabled = true;
            btn.innerHTML = `<i class='bx bx-loader-alt bx-spin'></i> Exporting...`;
        }

        try {
            const token = localStorage.getItem('sims_token') || localStorage.getItem('sims_access_token');
            const headers = {};
            if (token) {
                headers['Authorization'] = `Bearer ${token}`;
            }

            const response = await fetch(`${API_BASE_URL}/reports/export?report_type=Inventory`, {
                headers
            });

            if (response.status === 401) {
                Auth.logout();
                Utils.showToast("Session expired. Please login again.", "error");
                return;
            }

            if (response.status === 403) {
                Utils.showToast("Access denied: You do not have permission to export reports.", "error");
                return;
            }

            if (response.status === 423) {
                const errData = await response.json().catch(() => ({}));
                Utils.showToast(errData.message || "Report export is locked while inventory is being updated.", "warning");
                return;
            }

            if (!response.ok) {
                const errData = await response.json().catch(() => ({}));
                throw new Error(errData.error || `Export failed with status ${response.status}`);
            }

            const blob = await response.blob();
            
            // Extract filename from Content-Disposition header if available
            let filename = `current_inventory_report_${new Date().toISOString().slice(0, 10)}.csv`;
            const disposition = response.headers.get('Content-Disposition');
            if (disposition && disposition.includes('filename=')) {
                const match = disposition.match(/filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/);
                if (match && match[1]) {
                    filename = match[1].replace(/['"]/g, '').trim();
                }
            }

            // Create download link and trigger download
            const blobUrl = window.URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.style.display = 'none';
            a.href = blobUrl;
            a.download = filename;
            document.body.appendChild(a);
            a.click();
            window.URL.revokeObjectURL(blobUrl);
            a.remove();

            Utils.showToast("Current inventory report CSV downloaded successfully.", "success");
        } catch (error) {
            Utils.showToast(error.message || "Failed to export report CSV", "error");
        } finally {
            if (btn) {
                btn.disabled = false;
                btn.innerHTML = `<i class='bx bx-download'></i> Export CSV (Current Balance)`;
            }
        }
    }
};
