// View: Insights Section (Reports & Notifications)
const InsightsView = {
  // 1. Reports Generation & Archive
  renderReports() {
    return `
      <div class="view-section">
        <!-- System Readiness Gating Alert -->
        <div style="background-color: #ecfdf5; border: 1px solid #a7f3d0; border-radius: var(--radius-lg); padding: 16px 20px; margin-bottom: 20px; display: flex; align-items: center; justify-content: space-between;">
          <div style="display: flex; align-items: center; gap: 12px;">
            <div class="pulse-dot"></div>
            <div>
              <div style="font-weight: 700; color: #065f46; font-size: 14px;">Reporting Engine Status: READY</div>
              <div style="color: #047857; font-size: 12px;">Inventory sync is 100% complete. Safe for report generation.</div>
            </div>
          </div>
          <button class="btn-primary" onclick="App.openModal('modal-generate-report')">
            ${Icons.plus} Generate Inventory Report
          </button>
        </div>

        <div class="action-card">
          <div class="action-header">
            <div class="action-title-group">
              <h2>Generated Inventory Reports</h2>
              <p>Historical audit and inventory balance snapshots</p>
            </div>
            <div class="action-controls">
              <button class="btn-secondary" onclick="App.refreshReports()">
                ${Icons.status} Refresh
              </button>
            </div>
          </div>

          <div class="filter-bar">
            <div class="search-wrapper">
              <span class="search-icon-left">${Icons.search}</span>
              <input type="text" class="table-search-input" placeholder="Search reports..." oninput="App.filterTable(this, 'table-reports')"/>
            </div>
          </div>

          <div class="data-table-container">
            <table class="sims-table" id="table-reports">
              <thead>
                <tr>
                  <th style="width: 40px;"><input type="checkbox" class="table-checkbox" /></th>
                  <th>Report ID</th>
                  <th>Report Name</th>
                  <th>Report Type</th>
                  <th>Generated By</th>
                  <th>Generated Timestamp</th>
                  <th style="text-align: right;">Action</th>
                </tr>
              </thead>
              <tbody>
                ${Store.reports.map(r => `
                  <tr>
                    <td><input type="checkbox" class="table-checkbox" /></td>
                    <td><code>REP-00${r.report_id}</code></td>
                    <td>
                      <div class="entity-cell">
                        <div class="entity-icon-avatar" style="background: rgba(16, 185, 129, 0.12); color: #059669;">
                          ${Icons.reports}
                        </div>
                        <div class="entity-name">${r.report_name}</div>
                      </div>
                    </td>
                    <td><span class="status-pill role">${r.report_type}</span></td>
                    <td><strong>${r.generated_by}</strong></td>
                    <td style="color: #64748b;">${r.generated_on}</td>
                    <td style="text-align: right;">
                      <button class="btn-secondary" style="padding: 4px 10px; font-size: 12px;" onclick="App.viewReportDetails(${r.report_id})">
                        ${Icons.download} View / Export
                      </button>
                    </td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
          </div>

          <div class="pagination-bar">
            <div class="pagination-info">Showing 1 to ${Store.reports.length} of ${Store.reports.length} entries</div>
            <div class="pagination-controls">
              <button class="page-btn">${Icons.chevronLeft}</button>
              <button class="page-btn active">1</button>
              <button class="page-btn">${Icons.chevronRight}</button>
            </div>
          </div>
        </div>
      </div>
    `;
  },

  // 2. Notifications Center
  renderNotifications() {
    return `
      <div class="view-section">
        <div class="action-card">
          <div class="action-header">
            <div class="action-title-group">
              <h2>Notifications & System Alerts</h2>
              <p>Critical threshold warnings, purchase order completions, and operational alerts</p>
            </div>
            <div class="action-controls">
              <button class="btn-secondary" onclick="App.markAllNotificationsRead()">
                ${Icons.check} Mark All as Read
              </button>
            </div>
          </div>

          <div style="padding: 16px 24px;">
            <div style="display: flex; flex-direction: column; gap: 12px;">
              ${Store.notifications.map(n => {
                let badgeClass = "active";
                if (n.type === "WARNING") badgeClass = "lowstock";
                if (n.type === "INFO") badgeClass = "role";

                return `
                  <div style="display: flex; align-items: flex-start; justify-content: space-between; padding: 16px; border: 1px solid var(--border-color); border-radius: var(--radius-md); background-color: ${n.is_read ? '#ffffff' : '#f0fdf4'}; transition: all 0.15s ease;">
                    <div style="display: flex; align-items: flex-start; gap: 14px;">
                      <div class="entity-icon-avatar" style="margin-top: 2px;">
                        ${Icons.notifications}
                      </div>
                      <div>
                        <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 4px;">
                          <span style="font-weight: 700; color: var(--text-main); font-size: 14px;">${n.title}</span>
                          <span class="status-pill ${badgeClass}">${n.type}</span>
                          ${!n.is_read ? '<span style="font-size: 10px; font-weight: 700; background: #ef4444; color: #fff; padding: 1px 6px; border-radius: 9999px;">NEW</span>' : ''}
                        </div>
                        <div style="color: #475569; font-size: 13px; line-height: 1.4;">${n.message}</div>
                        <div style="color: #94a3b8; font-size: 11px; margin-top: 6px;">${n.time}</div>
                      </div>
                    </div>
                    <button class="action-icon-btn" title="Toggle Read" onclick="App.toggleNotificationRead(${n.notification_id})">
                      ${Icons.check}
                    </button>
                  </div>
                `;
              }).join('')}
            </div>
          </div>
        </div>
      </div>
    `;
  }
};

